import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          SSZ Visualizer
        </h1>

        <p className={styles.description}>
          Explore SSZ Types and Merkle Trees
        </p>

        <button className={`btn btn-primary`} style={{border: 'solid black'}}>
          <h2>
            START
          </h2>
        </button>

        <div className='p-4'><h4>Learn more about SSZ SimpleSerialize at <a  href='https://www.ssz.dev'>www.ssz.dev</a></h4></div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://esp.ethereum.foundation/en/"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src='/horz-logo-065bcbe38b2208c0239b3bc7c661258e.svg' alt="ESP Logo" width={200} height={100} />
          </span>
        </a>
      </footer>
    </div>
  )
}
